# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-22 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Armor',
        ),
    ]
