# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-14 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
