# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=12.99),
        ),
    ]
