# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160714_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.IntegerField(default=datetime.datetime(2016, 7, 15, 5, 44, 21, 114160, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
