# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20160721_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='in_stock',
            new_name='quantity',
        ),
    ]
