# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-23 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
